name: flutter_html_view
description: Flutter Plugin to render html, Flutter has no default support to render html so this package helps you to render your html to native widgets
version: 0.5.12
author: Karthik Ponnam <ponnamkarthik3@gmail.com>
homepage: https://github.com/PonnamKarthik/FlutterHtmlView

dependencies:
  flutter:
    sdk: flutter
  flutter_custom_tabs: ^0.6.0
  html: ^0.14.0+4
  video_player: ^1.0.1
  cached_network_image: ^2.3.3

  flutter_markdown: ^0.5.1
  html2md: ^0.5.1

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"
