name: flutter_html_view
description: Flutter Plugin to render html, Flutter has no default support to render html so this package helps you to render your html to native widgets
version: 0.5.12
author: Karthik Ponnam <ponnamkarthik3@gmail.com>
homepage: https://github.com/PonnamKarthik/FlutterHtmlView

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_custom_tabs: ^0.6.0
  html: ^0.15.0
  video_player: ^2.0.0
  cached_network_image: ^3.0.0-nullsafety

  flutter_markdown: ^0.6.0
  html2md: ^1.0.0

#dependency_overrides:
#  image: ^3.0.1

